---
# Variable configuration.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', first_found_params) }}"
  vars:
    first_found_params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
      paths:
        - 'vars'

- name: Define python_packages.
  ansible.builtin.set_fact:
    python_packages: "{{ __python_packages | list }}"
  when: python_packages is not defined

- name: Define python_version.
  ansible.builtin.set_fact:
    python_version: "{{ __python_version }}"
  when: python_version is not defined
